import type { AssetDefinition } from "../asset";
import { asset } from "../utils/asset";
import { blueprintAsset } from "../utils/blueprintAsset";

export const GameAssetDefinitions = [
	asset({
		id: "asset:item-seed",
		label: "Seed",
		fileName: "item-seed",
		sort: 10,
	}),
	asset({
		id: "asset:item-sprout",
		label: "Sprout",
		fileName: "item-sprout",
		sort: 20,
	}),
	asset({
		id: "asset:item-leaf",
		label: "Leaf",
		fileName: "item-leaf",
		sort: 30,
	}),
	asset({
		id: "asset:item-bush",
		label: "Bush",
		fileName: "item-bush",
		sort: 34,
	}),
	asset({
		id: "asset:item-sapling",
		label: "Sapling",
		fileName: "item-sapling",
		sort: 38,
	}),
	asset({
		id: "asset:item-tree",
		label: "Tree",
		fileName: "item-tree",
		sort: 39,
	}),
	asset({
		id: "asset:item-twig",
		label: "Twig",
		fileName: "item-twig",
		sort: 40,
	}),
	asset({
		id: "asset:item-branch",
		label: "Branch",
		fileName: "item-branch",
		sort: 50,
	}),
	asset({
		id: "asset:item-log",
		label: "Log",
		fileName: "item-log",
		sort: 60,
	}),
	asset({
		id: "asset:item-wood-bundle",
		label: "Wood Bundle",
		fileName: "item-wood-bundle",
		sort: 64,
	}),
	asset({
		id: "asset:item-plank",
		label: "Plank",
		fileName: "item-plank",
		sort: 66,
	}),
	asset({
		id: "asset:item-beam",
		label: "Beam",
		fileName: "item-beam",
		sort: 68,
	}),
	asset({
		id: "asset:item-pebble",
		label: "Pebble",
		fileName: "item-pebble",
		sort: 70,
	}),
	asset({
		id: "asset:item-stone",
		label: "Stone",
		fileName: "item-stone",
		sort: 80,
	}),
	asset({
		id: "asset:item-stone-block",
		label: "Stone Block",
		fileName: "item-stone-block",
		sort: 82,
	}),
	asset({
		id: "asset:item-ore",
		label: "Ore",
		fileName: "item-ore",
		sort: 84,
	}),
	asset({
		id: "asset:item-crystal",
		label: "Crystal",
		fileName: "item-crystal",
		sort: 90,
	}),
	asset({
		id: "asset:item-gem",
		label: "Gem",
		fileName: "item-gem",
		sort: 94,
	}),
	asset({
		id: "asset:item-water",
		label: "Water",
		fileName: "item-water",
		sort: 100,
	}),
	asset({
		id: "asset:item-coin",
		label: "Coin",
		fileName: "item-coin",
		sort: 101,
	}),
	asset({
		id: "asset:item-coin-pair",
		label: "Coin Pair",
		fileName: "item-coin-pair",
		sort: 102,
	}),
	asset({
		id: "asset:item-coin-stack",
		label: "Coin Stack",
		fileName: "item-coin-stack",
		sort: 103,
	}),
	asset({
		id: "asset:item-coin-chest",
		label: "Coin Chest",
		fileName: "item-coin-chest",
		sort: 104,
	}),
	asset({
		id: "asset:item-blueprint-scrap",
		label: "Blueprint Scrap",
		fileName: "item-blueprint-scrap",
		sort: 106,
	}),
	asset({
		id: "asset:item-blueprint-fragment",
		label: "Blueprint Fragment",
		fileName: "item-blueprint-fragment",
		sort: 108,
	}),
	asset({
		id: "asset:item-blueprint-draft",
		label: "Blueprint Draft",
		fileName: "item-blueprint-draft",
		sort: 110,
	}),
	asset({
		id: "asset:item-blueprint",
		label: "Finished Blueprint",
		fileName: "item-blueprint",
		sort: 112,
	}),
	blueprintAsset({
		id: "asset:item-blueprint-lumber-camp",
		label: "Lumber Camp Blueprint",
		overlayAssetId: "asset:item-lumber-camp",
		sort: 116,
	}),
	blueprintAsset({
		id: "asset:item-blueprint-quarry",
		label: "Quarry Blueprint",
		overlayAssetId: "asset:item-quarry",
		sort: 120,
	}),
	blueprintAsset({
		id: "asset:item-blueprint-townhall",
		label: "Town Hall Blueprint",
		overlayAssetId: "asset:item-townhall",
		sort: 124,
	}),
	asset({
		id: "asset:item-townhall",
		label: "Town Hall",
		fileName: "item-townhall",
		sort: 125,
	}),
	asset({
		id: "asset:item-lumber-camp",
		label: "Lumber Camp",
		fileName: "item-lumber-camp",
		sort: 130,
	}),
	asset({
		id: "asset:item-coal",
		label: "Coal",
		fileName: "item-coal",
		sort: 132,
	}),
	asset({
		id: "asset:item-sausage",
		label: "Sausage",
		fileName: "item-sausage",
		sort: 134,
	}),
	asset({
		id: "asset:item-beer",
		label: "Beer",
		fileName: "item-beer",
		sort: 136,
	}),
	asset({
		id: "asset:item-coal-mine",
		label: "Coal Mine",
		fileName: "item-coal-mine",
		sort: 138,
	}),
	asset({
		id: "asset:item-quarry",
		label: "Quarry",
		fileName: "item-quarry",
		sort: 140,
	}),
	asset({
		id: "asset:item-crate",
		label: "Common Crate",
		fileName: "item-crate",
		sort: 150,
	}),
	asset({
		id: "asset:item-crate-sturdy",
		label: "Sturdy Crate",
		fileName: "item-crate-sturdy",
		sort: 160,
	}),
	asset({
		id: "asset:item-crate-rare",
		label: "Rare Crate",
		fileName: "item-crate-rare",
		sort: 170,
	}),
	asset({
		id: "asset:item-crate-epic",
		label: "Epic Crate",
		fileName: "item-crate-epic",
		sort: 180,
	}),
	asset({
		id: "asset:item-epic-key",
		label: "Epic Key",
		fileName: "item-epic-key",
		sort: 182,
	}),
] satisfies readonly AssetDefinition[];
