import { z } from "zod";

export const GameAssetIdSchema = z.enum([
	"asset:item-seed",
	"asset:item-sprout",
	"asset:item-leaf",
	"asset:item-bush",
	"asset:item-sapling",
	"asset:item-tree",
	"asset:item-twig",
	"asset:item-branch",
	"asset:item-log",
	"asset:item-wood-bundle",
	"asset:item-plank",
	"asset:item-beam",
	"asset:item-pebble",
	"asset:item-stone",
	"asset:item-stone-block",
	"asset:item-ore",
	"asset:item-crystal",
	"asset:item-gem",
	"asset:item-water",
	"asset:item-coin",
	"asset:item-coin-pair",
	"asset:item-coin-stack",
	"asset:item-coin-chest",
	"asset:item-blueprint-scrap",
	"asset:item-blueprint-fragment",
	"asset:item-blueprint-draft",
	"asset:item-blueprint",
	"asset:item-blueprint-lumber-camp",
	"asset:item-lumber-camp",
	"asset:item-blueprint-quarry",
	"asset:item-quarry",
	"asset:item-blueprint-townhall",
	"asset:item-townhall",
	"asset:item-coal",
	"asset:item-sausage",
	"asset:item-beer",
	"asset:item-coal-mine",
	"asset:item-crate",
	"asset:item-crate-sturdy",
	"asset:item-crate-rare",
	"asset:item-crate-epic",
	"asset:item-epic-key",
]);

type GameAssetIdSchema = typeof GameAssetIdSchema;
export namespace GameAssetIdSchema {
	export type Type = z.infer<GameAssetIdSchema>;
}
