import { z } from "zod";

export const GameItemIdSchema = z.enum([
	"item:twig",
	"item:branch",
	"item:coin",
	"item:blueprint-scrap",
	"item:crate-1",
	"item:water",
	"item:crate-2",
	"item:blueprint-lumber-camp-2",
	"item:blueprint-quarry-2",
	"item:crate-3",
	"item:blueprint-lumber-camp-3",
	"item:blueprint-quarry-3",
	"item:crate-4",
	"item:blueprint-lumber-camp-4",
	"item:blueprint-quarry-4",
	"item:blueprint-lumber-camp-5",
	"item:blueprint-quarry-5",
	"item:log",
	"item:wood-bundle",
	"item:beam",
	"item:pebble",
	"item:stone",
	"item:crystal",
	"item:ore",
	"item:gem",
	"item:coal",
	"item:seed",
	"item:coin-pair",
	"item:coin-stack",
	"item:epic-key",
	"item:lumber-camp-1",
	"item:coin-chest",
	"item:quarry-1",
	"item:sprout",
	"item:leaf",
	"item:sapling",
	"item:bush",
	"item:tree",
	"item:plank",
	"item:stone-block",
	"item:sausage",
	"item:beer",
	"item:blueprint-fragment",
	"item:blueprint-draft",
	"item:blueprint",
	"item:blueprint-lumber-camp",
	"item:blueprint-quarry",
	"item:blueprint-townhall",
	"item:townhall-1",
	"item:lumber-camp-2",
	"item:lumber-camp-3",
	"item:lumber-camp-4",
	"item:lumber-camp-5",
	"item:quarry-2",
	"item:quarry-3",
	"item:quarry-4",
	"item:quarry-5",
	"item:blueprint-townhall-2",
	"item:townhall-2",
	"item:blueprint-townhall-3",
	"item:townhall-3",
	"item:blueprint-townhall-4",
	"item:townhall-4",
	"item:blueprint-townhall-5",
	"item:townhall-5",
	"item:coal-mine-1",
]);

type GameItemIdSchema = typeof GameItemIdSchema;
export namespace GameItemIdSchema {
	export type Type = z.infer<GameItemIdSchema>;
}
