const gameAudioEventIds = [
	"audio.ui.sheet.open",
	"audio.ui.sheet.close",
	"audio.ui.error",
	"audio.ui.reject.board",
	"audio.ui.reject.inventory",
	"audio.tile.drag.start",
	"audio.tile.drop.accept",
	"audio.tile.drop.reject",
	"audio.tile.long_press",
	"audio.inventory.place",
	"audio.board.stash",
	"audio.inventory.swap",
	"audio.board.move",
	"audio.board.swap",
	"audio.merge.success",
	"audio.merge.output",
	"audio.producer.input.store",
	"audio.producer.input.withdraw",
	"audio.producer.start",
	"audio.producer.complete",
	"audio.producer.blocked",
	"audio.producer.failed",
	"audio.producer.depleted",
	"audio.line.default_changed",
	"audio.stash.open.start",
	"audio.stash.release",
	"audio.craft.input.store",
	"audio.craft.input.withdraw",
	"audio.craft.start",
	"audio.craft.complete",
	"audio.craft.result.replace",
	"audio.craft.blocked",
	"audio.craft.failed",
	"audio.tile.remove",
	"audio.tile.remove.output",
	"audio.effect.activated",
	"audio.effect.expired",
	"audio.item.spawn.blocked",
	"audio.item.spawn.failed",
	"audio.debug.spawn.board",
	"audio.debug.spawn.inventory",
	"audio.cheat.speed.enable",
	"audio.cheat.speed.disable",
] as const;

export namespace GameAudioEvent {
	export type Id = (typeof gameAudioEventIds)[number];
}
