// Generated by `argc translations:sync`; edit src/translation/en.yaml instead.
import type { TranslationSchema } from "~/translation/schema/TranslationSchema";

export const EnglishTranslations = [
	{
		key: "Board editing",
		value: "Board editing",
	},
	{
		key: "Board editing help",
		value: "Every playable Space gets its own Board, but they all use the same **Width** and **Height**.\n\nUse **Space** to jump between Spaces 0–31. Switching is instant, so you can inspect every layout without saving between visits. Your edits stay attached to the selected Space.\n",
	},
	{
		key: "Close",
		value: "Close",
	},
	{
		key: "Estimate",
		value: "Estimate",
	},
	{
		key: "Inventory editing",
		value: "Inventory editing",
	},
	{
		key: "Inventory editing help",
		value: "Inventory is the shared passive storage available from every playable Space. **Width** and **Height** define the grid used everywhere.\n",
	},
	{
		key: "Item estimate help",
		value: "Estimate answers a practical question: **what would the game roughly need to obtain this item?** It follows starting items and production rules until it finds one complete route.\n\nThis is a planning preview, not a simulation or a promise.\n\n### Reading the result\n\n- Each row is an item needed somewhere along the selected route.\n- **Quantity** is the approximate amount the route consumes or requires.\n- **Time** is how much that part contributes to the optimistic total.\n- The Time and Quantity buttons only reorder the same result.\n\nArkini uses authored runtimes, output quantities and chances. Random outputs are converted into an expected number of attempts. Independent work can happen in parallel, so its time is not blindly added together.\n\nReal play may take longer or choose another route because player decisions, placement, timing and actual random rolls are not simulated. **Partial** or **unreachable** means the authored data did not provide one complete calculable path.\n",
	},
	{
		key: "Item required by help",
		value: "Required by answers: **which items genuinely need this item in order to work?**\n\nThe list includes direct production inputs and production conditions that require the item to exist. It deliberately excludes items that merely produce it, own its production line or return it as an output.\n\nOpen any row to continue exploring the same question for that item. An empty list means nothing currently consumes or requires this item, so it may be unnecessary authored data.\n",
	},
	{
		key: "Item storage scope - any",
		value: "Board, Inventory & Toolbar",
		dynamic: true,
	},
	{
		key: "Item storage scope - board",
		value: "Board only",
		dynamic: true,
	},
	{
		key: "Item storage scope - inventory",
		value: "Inventory only",
		dynamic: true,
	},
	{
		key: "Item storage scope - toolbar",
		value: "Toolbar only",
		dynamic: true,
	},
	{
		key: "Item type - blueprint",
		value: "Blueprint",
		dynamic: true,
	},
	{
		key: "Item type - craft",
		value: "Craft owner",
		dynamic: true,
	},
	{
		key: "Item type - deposit",
		value: "Resource deposit",
		dynamic: true,
	},
	{
		key: "Item type - inventory",
		value: "Inventory control",
		dynamic: true,
	},
	{
		key: "Item type - missing",
		value: "Missing item",
		dynamic: true,
	},
	{
		key: "Item type - producer",
		value: "Producer",
		dynamic: true,
	},
	{
		key: "Item type - simple",
		value: "Simple item",
		dynamic: true,
	},
	{
		key: "Item type - space",
		value: "Space item",
		dynamic: true,
	},
	{
		key: "Item type - stash",
		value: "Stash",
		dynamic: true,
	},
	{
		key: "Item type - temporary",
		value: "Temporary item",
		dynamic: true,
	},
	{
		key: "Item type description - blueprint",
		value: "A build plan with one construction line.",
		dynamic: true,
	},
	{
		key: "Item type description - craft",
		value: "A consumable or quest-like item with one product line.",
		dynamic: true,
	},
	{
		key: "Item type description - deposit",
		value: "A board resource source with optional finite production lines.",
		dynamic: true,
	},
	{
		key: "Item type description - inventory",
		value: "The singleton item that opens the shared inventory.",
		dynamic: true,
	},
	{
		key: "Item type description - producer",
		value: "A building or actor with one or more selectable product lines.",
		dynamic: true,
	},
	{
		key: "Item type description - simple",
		value: "A regular stackable item without specialized behavior.",
		dynamic: true,
	},
	{
		key: "Item type description - space",
		value: "An immediately activated item that moves play to an authored space.",
		dynamic: true,
	},
	{
		key: "Item type description - stash",
		value: "A chest or reward container with one opening line.",
		dynamic: true,
	},
	{
		key: "Item type description - temporary",
		value: "A board-only effect that expires after an authored duration.",
		dynamic: true,
	},
	{
		key: "Page help",
		value: "Page help",
	},
	{
		key: "Required by",
		value: "Required by",
	},
	{
		key: "Starting layout controls help",
		value: "### Starting layout controls\n\n- **Click** an empty slot to choose an item, or click a stack to add one.\n- **Right-click** a stack to remove it.\n- Hold **Alt/Cmd** and drag, or use **Alt/Cmd + Arrow**, to move a stack. Anything at the destination is replaced.\n- Press **Minus** to remove one item or **Delete** to remove the whole stack.\n",
	},
	{
		key: "Toolbar editing",
		value: "Toolbar editing",
	},
	{
		key: "Toolbar editing help",
		value: "Toolbar is passive one-row storage visible during play. Set **Slots** to zero if the game should not have one.\n",
	},
] as const satisfies readonly TranslationSchema.Type[];
