import { match, P } from "ts-pattern";
import { execFile } from "node:child_process";
import { constants } from "node:fs";
import { access } from "node:fs/promises";
import { resolve } from "node:path";
import { promisify } from "node:util";
import { Effect, Semaphore } from "effect";

import type { CompletionShell, CompletionStatus } from "~electron/contract/cli/CompletionStatus";
import { ElectronMainError } from "../ElectronMainError";
import { createManagedFileFx } from "./createManagedFileFx";

const execFileAsyncFn = promisify(execFile);
const managedCompletionPrefix = "# serakki-cli managed completion\n";

/** Main-process ownership of one user-level shell completion file. */
export interface Completion {
	readonly readStatusFx: Effect.Effect<CompletionStatus, ElectronMainError, never>;
	readonly installFx: Effect.Effect<CompletionStatus, ElectronMainError, never>;
	readonly replaceFx: Effect.Effect<CompletionStatus, ElectronMainError, never>;
	readonly uninstallFx: Effect.Effect<CompletionStatus, ElectronMainError, never>;
}

export namespace createCompletionFx {
	export interface Props {
		readonly completion?: {
			readonly path: string;
			readonly shell: CompletionShell;
		};
		readonly launcherPath: string;
		readonly unavailableMessage?: string;
	}
}

/** Creates the owned shell-completion file generated by the packaged CLI command tree. */
export const createCompletionFx = Effect.fn("createCompletionFx")(function* ({
	completion,
	launcherPath,
	unavailableMessage,
}: createCompletionFx.Props) {
	const semaphore = yield* Semaphore.make(1);
	const resolvedLauncherPath = resolve(launcherPath);
	const readGeneratedContentsFn = async () => {
		if (completion === undefined) throw new Error("The current shell is unsupported.");
		const { stdout } = await execFileAsyncFn(
			resolvedLauncherPath,
			[
				"--completions",
				completion.shell,
			],
			{
				encoding: "utf8",
				maxBuffer: 2 * 1024 * 1024,
				timeout: 10_000,
			},
		);
		return `${managedCompletionPrefix}${stdout}`;
	};
	const managedFile = yield* completion === undefined
		? Effect.succeed(undefined)
		: createManagedFileFx({
				path: completion.path,
				managedPrefix: managedCompletionPrefix,
				mode: 0o644,
				subject: "Shell completion",
				readExpectedContentsFn: readGeneratedContentsFn,
			});
	const requireManagedFileFn = () => {
		if (managedFile === undefined) throw new Error("The current shell is unsupported.");
		return managedFile;
	};

	const readStatusFn = async (): Promise<CompletionStatus> => {
		if (unavailableMessage !== undefined) {
			return {
				type: "unavailable",
				message: unavailableMessage,
			};
		}
		if (completion === undefined) {
			return {
				type: "unavailable",
				message: "Shell completion installation is available for Bash, Fish, and Zsh.",
			};
		}
		try {
			await access(resolvedLauncherPath, constants.X_OK);
		} catch (cause) {
			return {
				type: "unavailable",
				message: `The packaged serakki-cli launcher is unavailable: ${String(cause)}`,
			};
		}
		const inspection = await requireManagedFileFn().inspectFn();
		return match(inspection)
			.returnType<CompletionStatus>()
			.with(
				{
					type: "conflict",
				},
				(inspection) => ({
					type: "conflict",
					completionPath: completion.path,
					shell: completion.shell,
					message: inspection.message,
					replaceable: inspection.replaceable,
				}),
			)
			.with(
				{
					type: "repairable",
				},
				() => ({
					type: "repairable",
					completionPath: completion.path,
					shell: completion.shell,
					message: `${completion.shell} completion no longer matches this Serakki installation.`,
				}),
			)
			.with(
				{
					type: "installed",
				},
				() => ({
					type: "installed",
					completionPath: completion.path,
					shell: completion.shell,
				}),
			)
			.with(
				{
					type: "missing",
				},
				() => ({
					type: "not-installed",
					completionPath: completion.path,
					shell: completion.shell,
				}),
			)
			.exhaustive();
	};

	const operationFx = (name: string, runFn: () => Promise<CompletionStatus>) =>
		Effect.tryPromise({
			try: runFn,
			catch: (cause) =>
				new ElectronMainError({
					operation: name,
					cause,
				}),
		});

	const readStatusFx = operationFx("read the CLI completion installation", readStatusFn);
	const installFx = semaphore.withPermits(1)(
		operationFx("install CLI shell completion", async () => {
			return match(await readStatusFn())
				.returnType<CompletionStatus | Promise<CompletionStatus>>()
				.with(
					{
						type: "installed",
					},
					(status) => status,
				)
				.with(
					{
						type: P.union("unavailable", "conflict"),
					},
					(status) => {
						throw new Error(status.message);
					},
				)
				.with(
					{
						type: "repairable",
					},
					async () => {
						await requireManagedFileFn().repairFn();
						return readStatusFn();
					},
				)
				.with(
					{
						type: "not-installed",
					},
					async () => {
						await requireManagedFileFn().publishFn(false);
						return readStatusFn();
					},
				)
				.exhaustive();
		}),
	);
	const replaceFx = semaphore.withPermits(1)(
		operationFx("replace CLI shell completion", async () => {
			return match(await readStatusFn())
				.returnType<CompletionStatus | Promise<CompletionStatus>>()
				.with(
					{
						type: "installed",
					},
					(status) => status,
				)
				.with(
					{
						type: "unavailable",
					},
					{
						type: "conflict",
						replaceable: false,
					},
					(status) => {
						throw new Error(status.message);
					},
				)
				.with(
					{
						type: P.union("conflict", "repairable", "not-installed"),
					},
					async (status) => {
						await requireManagedFileFn().publishFn(status.type !== "not-installed");
						return readStatusFn();
					},
				)
				.exhaustive();
		}),
	);
	const uninstallFx = semaphore.withPermits(1)(
		operationFx("uninstall CLI shell completion", async () => {
			return match(await readStatusFn())
				.returnType<CompletionStatus | Promise<CompletionStatus>>()
				.with(
					{
						type: "not-installed",
					},
					(status) => status,
				)
				.with(
					{
						type: P.union("unavailable", "conflict"),
					},
					(status) => {
						throw new Error(status.message);
					},
				)
				.with(
					{
						type: P.union("installed", "repairable"),
					},
					async () => {
						await requireManagedFileFn().removeFn();
						return readStatusFn();
					},
				)
				.exhaustive();
		}),
	);

	return {
		readStatusFx,
		installFx,
		replaceFx,
		uninstallFx,
	} satisfies Completion;
});
