import { execFile } from "node:child_process";
import { constants } from "node:fs";
import { access } from "node:fs/promises";
import { resolve } from "node:path";
import { promisify } from "node:util";
import { Effect, Semaphore } from "effect";

import type { CompletionShell, CompletionStatus } from "../../contract/cli/CompletionStatus";
import { ElectronMainError } from "../ElectronMainError";
import { createManagedFileFx } from "./createManagedFileFx";

const execFileAsync = promisify(execFile);
const managedCompletionPrefix = "# arkini-cli managed completion\n";

/** Main-process ownership of one user-level shell completion file. */
export interface Completion {
	readonly readStatusFx: Effect.Effect<CompletionStatus, ElectronMainError>;
	readonly installFx: Effect.Effect<CompletionStatus, ElectronMainError>;
	readonly replaceFx: Effect.Effect<CompletionStatus, ElectronMainError>;
	readonly uninstallFx: Effect.Effect<CompletionStatus, ElectronMainError>;
}

export namespace createCompletionFx {
	export interface Props {
		readonly completion?: {
			readonly path: string;
			readonly shell: CompletionShell;
		};
		readonly launcherPath: string;
		readonly unavailableMessage?: string;
	}
}

/** Creates the owned shell-completion file generated by the packaged CLI command tree. */
export const createCompletionFx = Effect.fn("createCompletionFx")(function* ({
	completion,
	launcherPath,
	unavailableMessage,
}: createCompletionFx.Props) {
	const semaphore = yield* Semaphore.make(1);
	const resolvedLauncherPath = resolve(launcherPath);
	const readGeneratedContents = async () => {
		if (completion === undefined) throw new Error("The current shell is unsupported.");
		const { stdout } = await execFileAsync(
			resolvedLauncherPath,
			[
				"--completions",
				completion.shell,
			],
			{
				encoding: "utf8",
				maxBuffer: 2 * 1024 * 1024,
				timeout: 10_000,
			},
		);
		return `${managedCompletionPrefix}${stdout}`;
	};
	const managedFile = yield* completion === undefined
		? Effect.succeed(undefined)
		: createManagedFileFx({
				path: completion.path,
				managedPrefix: managedCompletionPrefix,
				mode: 0o644,
				subject: "Shell completion",
				readExpectedContents: readGeneratedContents,
			});
	const requireManagedFile = () => {
		if (managedFile === undefined) throw new Error("The current shell is unsupported.");
		return managedFile;
	};

	const readStatus = async (): Promise<CompletionStatus> => {
		if (unavailableMessage !== undefined) {
			return {
				type: "unavailable",
				message: unavailableMessage,
			};
		}
		if (completion === undefined) {
			return {
				type: "unavailable",
				message: "Shell completion installation is available for Bash, Fish, and Zsh.",
			};
		}
		try {
			await access(resolvedLauncherPath, constants.X_OK);
		} catch (cause) {
			return {
				type: "unavailable",
				message: `The packaged arkini-cli launcher is unavailable: ${String(cause)}`,
			};
		}
		const inspection = await requireManagedFile().inspect();
		if (inspection.type === "conflict") {
			return {
				type: "conflict",
				completionPath: completion.path,
				shell: completion.shell,
				message: inspection.message,
				replaceable: inspection.replaceable,
			};
		}
		if (inspection.type === "repairable") {
			return {
				type: "repairable",
				completionPath: completion.path,
				shell: completion.shell,
				message: `${completion.shell} completion no longer matches this Arkini installation.`,
			};
		}
		return {
			type: inspection.type === "installed" ? "installed" : "not-installed",
			completionPath: completion.path,
			shell: completion.shell,
		};
	};

	const operation = (name: string, run: () => Promise<CompletionStatus>) =>
		Effect.tryPromise({
			try: run,
			catch: (cause) =>
				new ElectronMainError({
					operation: name,
					cause,
				}),
		});

	const readStatusFx = operation("read the CLI completion installation", readStatus);
	const installFx = semaphore.withPermits(1)(
		operation("install CLI shell completion", async () => {
			const status = await readStatus();
			if (status.type === "installed") return status;
			if (status.type !== "not-installed" && status.type !== "repairable") {
				throw new Error(status.message);
			}
			if (status.type === "repairable") {
				await requireManagedFile().repair();
			} else {
				await requireManagedFile().publish(false);
			}
			return readStatus();
		}),
	);
	const replaceFx = semaphore.withPermits(1)(
		operation("replace CLI shell completion", async () => {
			const status = await readStatus();
			if (status.type === "installed") return status;
			if (status.type === "unavailable") throw new Error(status.message);
			if (status.type === "conflict" && !status.replaceable) {
				throw new Error(status.message);
			}
			await requireManagedFile().publish(status.type !== "not-installed");
			return readStatus();
		}),
	);
	const uninstallFx = semaphore.withPermits(1)(
		operation("uninstall CLI shell completion", async () => {
			const status = await readStatus();
			if (status.type === "not-installed") return status;
			if (status.type !== "installed" && status.type !== "repairable") {
				throw new Error(status.message);
			}
			await requireManagedFile().remove();
			return readStatus();
		}),
	);

	return {
		readStatusFx,
		installFx,
		replaceFx,
		uninstallFx,
	} satisfies Completion;
});
