/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./@routes/__root"
import { Route as GameRouteImport } from "./@routes/game"
import { Route as GameIndexRouteImport } from "./@routes/game/index"

const GameRoute = GameRouteImport.update({
  id: "/game",
  path: "/game",
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  "/game": typeof GameRouteWithChildren
  "/game/": typeof GameIndexRoute
}
export interface FileRoutesByTo {
  "/game": typeof GameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/game": typeof GameRouteWithChildren
  "/game/": typeof GameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/game" | "/game/"
  fileRoutesByTo: FileRoutesByTo
  to: "/game"
  id: "__root__" | "/game" | "/game/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GameRoute: typeof GameRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/game": {
      id: "/game"
      path: "/game"
      fullPath: "/game"
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/game/": {
      id: "/game/"
      path: "/"
      fullPath: "/game/"
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface GameRouteChildren {
  GameIndexRoute: typeof GameIndexRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameIndexRoute: GameIndexRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GameRoute: GameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
