/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./@routes/__root"
import { Route as LauncherRouteImport } from "./@routes/_launcher"
import { Route as IndexRouteImport } from "./@routes/index"
import { Route as GamePackageIdRouteImport } from "./@routes/game/$packageId"
import { Route as ActionRecoverGameSaveRouteImport } from "./@routes/action/recover-game-save"
import { Route as LauncherSettingsRouteImport } from "./@routes/_launcher/settings"
import { Route as LauncherMainMenuRouteImport } from "./@routes/_launcher/main-menu"
import { Route as LauncherArkpacksRouteImport } from "./@routes/_launcher/arkpacks"
import { Route as LauncherAboutRouteImport } from "./@routes/_launcher/about"
import { Route as GamePackageIdBoardRouteImport } from "./@routes/game/$packageId/board"
import { Route as ActionLoadGamePackageIdRouteImport } from "./@routes/action/load-game/$packageId"
import { Route as GamePackageIdActionResetRouteImport } from "./@routes/game/$packageId/action/reset"
import { Route as GamePackageIdActionLeaveRouteImport } from "./@routes/game/$packageId/action/leave"

const LauncherRoute = LauncherRouteImport.update({
  id: "/_launcher",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const GamePackageIdRoute = GamePackageIdRouteImport.update({
  id: "/game/$packageId",
  path: "/game/$packageId",
  getParentRoute: () => rootRouteImport,
} as any)
const ActionRecoverGameSaveRoute = ActionRecoverGameSaveRouteImport.update({
  id: "/action/recover-game-save",
  path: "/action/recover-game-save",
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherSettingsRoute = LauncherSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => LauncherRoute,
} as any)
const LauncherMainMenuRoute = LauncherMainMenuRouteImport.update({
  id: "/main-menu",
  path: "/main-menu",
  getParentRoute: () => LauncherRoute,
} as any)
const LauncherArkpacksRoute = LauncherArkpacksRouteImport.update({
  id: "/arkpacks",
  path: "/arkpacks",
  getParentRoute: () => LauncherRoute,
} as any)
const LauncherAboutRoute = LauncherAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => LauncherRoute,
} as any)
const GamePackageIdBoardRoute = GamePackageIdBoardRouteImport.update({
  id: "/board",
  path: "/board",
  getParentRoute: () => GamePackageIdRoute,
} as any)
const ActionLoadGamePackageIdRoute = ActionLoadGamePackageIdRouteImport.update({
  id: "/action/load-game/$packageId",
  path: "/action/load-game/$packageId",
  getParentRoute: () => rootRouteImport,
} as any)
const GamePackageIdActionResetRoute =
  GamePackageIdActionResetRouteImport.update({
    id: "/action/reset",
    path: "/action/reset",
    getParentRoute: () => GamePackageIdRoute,
  } as any)
const GamePackageIdActionLeaveRoute =
  GamePackageIdActionLeaveRouteImport.update({
    id: "/action/leave",
    path: "/action/leave",
    getParentRoute: () => GamePackageIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof LauncherAboutRoute
  "/arkpacks": typeof LauncherArkpacksRoute
  "/main-menu": typeof LauncherMainMenuRoute
  "/settings": typeof LauncherSettingsRoute
  "/action/recover-game-save": typeof ActionRecoverGameSaveRoute
  "/game/$packageId": typeof GamePackageIdRouteWithChildren
  "/action/load-game/$packageId": typeof ActionLoadGamePackageIdRoute
  "/game/$packageId/board": typeof GamePackageIdBoardRoute
  "/game/$packageId/action/leave": typeof GamePackageIdActionLeaveRoute
  "/game/$packageId/action/reset": typeof GamePackageIdActionResetRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof LauncherAboutRoute
  "/arkpacks": typeof LauncherArkpacksRoute
  "/main-menu": typeof LauncherMainMenuRoute
  "/settings": typeof LauncherSettingsRoute
  "/action/recover-game-save": typeof ActionRecoverGameSaveRoute
  "/game/$packageId": typeof GamePackageIdRouteWithChildren
  "/action/load-game/$packageId": typeof ActionLoadGamePackageIdRoute
  "/game/$packageId/board": typeof GamePackageIdBoardRoute
  "/game/$packageId/action/leave": typeof GamePackageIdActionLeaveRoute
  "/game/$packageId/action/reset": typeof GamePackageIdActionResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_launcher": typeof LauncherRouteWithChildren
  "/_launcher/about": typeof LauncherAboutRoute
  "/_launcher/arkpacks": typeof LauncherArkpacksRoute
  "/_launcher/main-menu": typeof LauncherMainMenuRoute
  "/_launcher/settings": typeof LauncherSettingsRoute
  "/action/recover-game-save": typeof ActionRecoverGameSaveRoute
  "/game/$packageId": typeof GamePackageIdRouteWithChildren
  "/action/load-game/$packageId": typeof ActionLoadGamePackageIdRoute
  "/game/$packageId/board": typeof GamePackageIdBoardRoute
  "/game/$packageId/action/leave": typeof GamePackageIdActionLeaveRoute
  "/game/$packageId/action/reset": typeof GamePackageIdActionResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/arkpacks"
    | "/main-menu"
    | "/settings"
    | "/action/recover-game-save"
    | "/game/$packageId"
    | "/action/load-game/$packageId"
    | "/game/$packageId/board"
    | "/game/$packageId/action/leave"
    | "/game/$packageId/action/reset"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/about"
    | "/arkpacks"
    | "/main-menu"
    | "/settings"
    | "/action/recover-game-save"
    | "/game/$packageId"
    | "/action/load-game/$packageId"
    | "/game/$packageId/board"
    | "/game/$packageId/action/leave"
    | "/game/$packageId/action/reset"
  id:
    | "__root__"
    | "/"
    | "/_launcher"
    | "/_launcher/about"
    | "/_launcher/arkpacks"
    | "/_launcher/main-menu"
    | "/_launcher/settings"
    | "/action/recover-game-save"
    | "/game/$packageId"
    | "/action/load-game/$packageId"
    | "/game/$packageId/board"
    | "/game/$packageId/action/leave"
    | "/game/$packageId/action/reset"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LauncherRoute: typeof LauncherRouteWithChildren
  ActionRecoverGameSaveRoute: typeof ActionRecoverGameSaveRoute
  GamePackageIdRoute: typeof GamePackageIdRouteWithChildren
  ActionLoadGamePackageIdRoute: typeof ActionLoadGamePackageIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_launcher": {
      id: "/_launcher"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof LauncherRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/game/$packageId": {
      id: "/game/$packageId"
      path: "/game/$packageId"
      fullPath: "/game/$packageId"
      preLoaderRoute: typeof GamePackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/action/recover-game-save": {
      id: "/action/recover-game-save"
      path: "/action/recover-game-save"
      fullPath: "/action/recover-game-save"
      preLoaderRoute: typeof ActionRecoverGameSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_launcher/settings": {
      id: "/_launcher/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof LauncherSettingsRouteImport
      parentRoute: typeof LauncherRoute
    }
    "/_launcher/main-menu": {
      id: "/_launcher/main-menu"
      path: "/main-menu"
      fullPath: "/main-menu"
      preLoaderRoute: typeof LauncherMainMenuRouteImport
      parentRoute: typeof LauncherRoute
    }
    "/_launcher/arkpacks": {
      id: "/_launcher/arkpacks"
      path: "/arkpacks"
      fullPath: "/arkpacks"
      preLoaderRoute: typeof LauncherArkpacksRouteImport
      parentRoute: typeof LauncherRoute
    }
    "/_launcher/about": {
      id: "/_launcher/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof LauncherAboutRouteImport
      parentRoute: typeof LauncherRoute
    }
    "/game/$packageId/board": {
      id: "/game/$packageId/board"
      path: "/board"
      fullPath: "/game/$packageId/board"
      preLoaderRoute: typeof GamePackageIdBoardRouteImport
      parentRoute: typeof GamePackageIdRoute
    }
    "/action/load-game/$packageId": {
      id: "/action/load-game/$packageId"
      path: "/action/load-game/$packageId"
      fullPath: "/action/load-game/$packageId"
      preLoaderRoute: typeof ActionLoadGamePackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/game/$packageId/action/reset": {
      id: "/game/$packageId/action/reset"
      path: "/action/reset"
      fullPath: "/game/$packageId/action/reset"
      preLoaderRoute: typeof GamePackageIdActionResetRouteImport
      parentRoute: typeof GamePackageIdRoute
    }
    "/game/$packageId/action/leave": {
      id: "/game/$packageId/action/leave"
      path: "/action/leave"
      fullPath: "/game/$packageId/action/leave"
      preLoaderRoute: typeof GamePackageIdActionLeaveRouteImport
      parentRoute: typeof GamePackageIdRoute
    }
  }
}

interface LauncherRouteChildren {
  LauncherAboutRoute: typeof LauncherAboutRoute
  LauncherArkpacksRoute: typeof LauncherArkpacksRoute
  LauncherMainMenuRoute: typeof LauncherMainMenuRoute
  LauncherSettingsRoute: typeof LauncherSettingsRoute
}

const LauncherRouteChildren: LauncherRouteChildren = {
  LauncherAboutRoute: LauncherAboutRoute,
  LauncherArkpacksRoute: LauncherArkpacksRoute,
  LauncherMainMenuRoute: LauncherMainMenuRoute,
  LauncherSettingsRoute: LauncherSettingsRoute,
}

const LauncherRouteWithChildren = LauncherRoute._addFileChildren(
  LauncherRouteChildren,
)

interface GamePackageIdRouteChildren {
  GamePackageIdBoardRoute: typeof GamePackageIdBoardRoute
  GamePackageIdActionLeaveRoute: typeof GamePackageIdActionLeaveRoute
  GamePackageIdActionResetRoute: typeof GamePackageIdActionResetRoute
}

const GamePackageIdRouteChildren: GamePackageIdRouteChildren = {
  GamePackageIdBoardRoute: GamePackageIdBoardRoute,
  GamePackageIdActionLeaveRoute: GamePackageIdActionLeaveRoute,
  GamePackageIdActionResetRoute: GamePackageIdActionResetRoute,
}

const GamePackageIdRouteWithChildren = GamePackageIdRoute._addFileChildren(
  GamePackageIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LauncherRoute: LauncherRouteWithChildren,
  ActionRecoverGameSaveRoute: ActionRecoverGameSaveRoute,
  GamePackageIdRoute: GamePackageIdRouteWithChildren,
  ActionLoadGamePackageIdRoute: ActionLoadGamePackageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
