/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./@routes/__root"
import { Route as EditorRouteImport } from "./@routes/editor"
import { Route as LauncherRouteImport } from "./@routes/_launcher"
import { Route as IndexRouteImport } from "./@routes/index"
import { Route as GamePackageIdRouteImport } from "./@routes/game/$packageId"
import { Route as EditorWelcomeRouteImport } from "./@routes/editor/welcome"
import { Route as EditorProjectIdRouteImport } from "./@routes/editor/$projectId"
import { Route as ActionRecoverGameSaveRouteImport } from "./@routes/action/recover-game-save"
import { Route as ActionDiscardFailedGameRouteImport } from "./@routes/action/discard-failed-game"
import { Route as LauncherSettingsRouteImport } from "./@routes/_launcher/settings"
import { Route as LauncherMainMenuRouteImport } from "./@routes/_launcher/main-menu"
import { Route as LauncherArkpacksRouteImport } from "./@routes/_launcher/arkpacks"
import { Route as LauncherAboutRouteImport } from "./@routes/_launcher/about"
import { Route as GamePackageIdCheatsRouteImport } from "./@routes/game/$packageId/cheats"
import { Route as GamePackageIdSceneRouteImport } from "./@routes/game/$packageId/_scene"
import { Route as EditorProjectIdProjectRouteImport } from "./@routes/editor/$projectId/project"
import { Route as EditorProjectIdEditorRouteImport } from "./@routes/editor/$projectId/editor"
import { Route as EditorProjectIdBuildRouteImport } from "./@routes/editor/$projectId/build"
import { Route as EditorProjectIdBoardRouteImport } from "./@routes/editor/$projectId/board"
import { Route as EditorProjectIdAssetsRouteImport } from "./@routes/editor/$projectId/assets"
import { Route as ActionLoadGamePackageIdRouteImport } from "./@routes/action/load-game/$packageId"
import { Route as EditorProjectIdEditorIndexRouteImport } from "./@routes/editor/$projectId/editor/index"
import { Route as GamePackageIdActionResetRouteImport } from "./@routes/game/$packageId/action/reset"
import { Route as GamePackageIdActionLeaveRouteImport } from "./@routes/game/$packageId/action/leave"
import { Route as GamePackageIdActionExitRouteImport } from "./@routes/game/$packageId/action/exit"
import { Route as GamePackageIdSceneInventoryRouteImport } from "./@routes/game/$packageId/_scene/inventory"
import { Route as GamePackageIdSceneBoardRouteImport } from "./@routes/game/$packageId/_scene/board"
import { Route as EditorProjectIdEditorItemsRouteImport } from "./@routes/editor/$projectId/editor/items"
import { Route as EditorProjectIdEditorItemsListRouteImport } from "./@routes/editor/$projectId/editor/items/list"
import { Route as EditorProjectIdEditorItemsItemUidRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid"
import { Route as EditorProjectIdEditorItemsItemUidCreateRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/create"
import { Route as EditorProjectIdEditorItemsItemUidEditRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/edit"
import { Route as EditorProjectIdEditorItemsItemUidCreateIndexRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/create/index"
import { Route as EditorProjectIdEditorItemsItemUidCreateIdentityRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/create/identity"
import { Route as EditorProjectIdEditorItemsItemUidCreateArtworkRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/create/artwork"
import { Route as EditorProjectIdEditorItemsItemUidCreateLimitsRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/create/limits"
import { Route as EditorProjectIdEditorItemsItemUidCreateChargesRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/create/charges"
import { Route as EditorProjectIdEditorItemsItemUidCreateMergesRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/create/merges"
import { Route as EditorProjectIdEditorItemsItemUidCreateProductionRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/create/production"
import { Route as EditorProjectIdEditorItemsItemUidEditIndexRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/edit/index"
import { Route as EditorProjectIdEditorItemsItemUidEditIdentityRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/edit/identity"
import { Route as EditorProjectIdEditorItemsItemUidEditArtworkRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/edit/artwork"
import { Route as EditorProjectIdEditorItemsItemUidEditLimitsRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/edit/limits"
import { Route as EditorProjectIdEditorItemsItemUidEditChargesRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/edit/charges"
import { Route as EditorProjectIdEditorItemsItemUidEditMergesRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/edit/merges"
import { Route as EditorProjectIdEditorItemsItemUidEditProductionRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/edit/production"
import { Route as EditorProjectIdEditorItemsItemUidViewRouteImport } from "./@routes/editor/$projectId/editor/items/$itemUid/view"
import { Route as EditorProjectIdEditorItemsNewRouteImport } from "./@routes/editor/$projectId/editor/items/new"
import { Route as EditorProjectIdEditorItemsNewSelectRouteImport } from "./@routes/editor/$projectId/editor/items/new/select"

const EditorRoute = EditorRouteImport.update({
  id: "/editor",
  path: "/editor",
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherRoute = LauncherRouteImport.update({
  id: "/_launcher",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const GamePackageIdRoute = GamePackageIdRouteImport.update({
  id: "/game/$packageId",
  path: "/game/$packageId",
  getParentRoute: () => rootRouteImport,
} as any)
const EditorWelcomeRoute = EditorWelcomeRouteImport.update({
  id: "/welcome",
  path: "/welcome",
  getParentRoute: () => EditorRoute,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: "/$projectId",
  path: "/$projectId",
  getParentRoute: () => EditorRoute,
} as any)
const ActionRecoverGameSaveRoute = ActionRecoverGameSaveRouteImport.update({
  id: "/action/recover-game-save",
  path: "/action/recover-game-save",
  getParentRoute: () => rootRouteImport,
} as any)
const ActionDiscardFailedGameRoute = ActionDiscardFailedGameRouteImport.update({
  id: "/action/discard-failed-game",
  path: "/action/discard-failed-game",
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherSettingsRoute = LauncherSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => LauncherRoute,
} as any)
const LauncherMainMenuRoute = LauncherMainMenuRouteImport.update({
  id: "/main-menu",
  path: "/main-menu",
  getParentRoute: () => LauncherRoute,
} as any)
const LauncherArkpacksRoute = LauncherArkpacksRouteImport.update({
  id: "/arkpacks",
  path: "/arkpacks",
  getParentRoute: () => LauncherRoute,
} as any)
const LauncherAboutRoute = LauncherAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => LauncherRoute,
} as any)
const GamePackageIdCheatsRoute = GamePackageIdCheatsRouteImport.update({
  id: "/cheats",
  path: "/cheats",
  getParentRoute: () => GamePackageIdRoute,
} as any)
const GamePackageIdSceneRoute = GamePackageIdSceneRouteImport.update({
  id: "/_scene",
  getParentRoute: () => GamePackageIdRoute,
} as any)
const EditorProjectIdProjectRoute = EditorProjectIdProjectRouteImport.update({
  id: "/project",
  path: "/project",
  getParentRoute: () => EditorProjectIdRoute,
} as any)
const EditorProjectIdEditorRoute = EditorProjectIdEditorRouteImport.update({
  id: "/editor",
  path: "/editor",
  getParentRoute: () => EditorProjectIdRoute,
} as any)
const EditorProjectIdBuildRoute = EditorProjectIdBuildRouteImport.update({
  id: "/build",
  path: "/build",
  getParentRoute: () => EditorProjectIdRoute,
} as any)
const EditorProjectIdBoardRoute = EditorProjectIdBoardRouteImport.update({
  id: "/board",
  path: "/board",
  getParentRoute: () => EditorProjectIdRoute,
} as any)
const EditorProjectIdAssetsRoute = EditorProjectIdAssetsRouteImport.update({
  id: "/assets",
  path: "/assets",
  getParentRoute: () => EditorProjectIdRoute,
} as any)
const ActionLoadGamePackageIdRoute = ActionLoadGamePackageIdRouteImport.update({
  id: "/action/load-game/$packageId",
  path: "/action/load-game/$packageId",
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdEditorIndexRoute = EditorProjectIdEditorIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => EditorProjectIdEditorRoute,
} as any)
const GamePackageIdActionResetRoute = GamePackageIdActionResetRouteImport.update({
  id: "/action/reset",
  path: "/action/reset",
  getParentRoute: () => GamePackageIdRoute,
} as any)
const GamePackageIdActionLeaveRoute = GamePackageIdActionLeaveRouteImport.update({
  id: "/action/leave",
  path: "/action/leave",
  getParentRoute: () => GamePackageIdRoute,
} as any)
const GamePackageIdActionExitRoute = GamePackageIdActionExitRouteImport.update({
  id: "/action/exit",
  path: "/action/exit",
  getParentRoute: () => GamePackageIdRoute,
} as any)
const GamePackageIdSceneInventoryRoute = GamePackageIdSceneInventoryRouteImport.update({
  id: "/inventory",
  path: "/inventory",
  getParentRoute: () => GamePackageIdSceneRoute,
} as any)
const GamePackageIdSceneBoardRoute = GamePackageIdSceneBoardRouteImport.update({
  id: "/board",
  path: "/board",
  getParentRoute: () => GamePackageIdSceneRoute,
} as any)
const EditorProjectIdEditorItemsRoute = EditorProjectIdEditorItemsRouteImport.update({
  id: "/items",
  path: "/items",
  getParentRoute: () => EditorProjectIdEditorRoute,
} as any)
const EditorProjectIdEditorItemsListRoute = EditorProjectIdEditorItemsListRouteImport.update({
  id: "/list",
  path: "/list",
  getParentRoute: () => EditorProjectIdEditorItemsRoute,
} as any)
const EditorProjectIdEditorItemsItemUidRoute = EditorProjectIdEditorItemsItemUidRouteImport.update({
  id: "/$itemUid",
  path: "/$itemUid",
  getParentRoute: () => EditorProjectIdEditorItemsRoute,
} as any)
const EditorProjectIdEditorItemsItemUidCreateRoute = EditorProjectIdEditorItemsItemUidCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidRoute,
} as any)
const EditorProjectIdEditorItemsItemUidEditRoute = EditorProjectIdEditorItemsItemUidEditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidRoute,
} as any)

const EditorProjectIdEditorItemsItemUidCreateIndexRoute = EditorProjectIdEditorItemsItemUidCreateIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidCreateRoute,
} as any)
const EditorProjectIdEditorItemsItemUidCreateIdentityRoute = EditorProjectIdEditorItemsItemUidCreateIdentityRouteImport.update({
  id: "/identity",
  path: "/identity",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidCreateRoute,
} as any)
const EditorProjectIdEditorItemsItemUidCreateArtworkRoute = EditorProjectIdEditorItemsItemUidCreateArtworkRouteImport.update({
  id: "/artwork",
  path: "/artwork",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidCreateRoute,
} as any)
const EditorProjectIdEditorItemsItemUidCreateLimitsRoute = EditorProjectIdEditorItemsItemUidCreateLimitsRouteImport.update({
  id: "/limits",
  path: "/limits",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidCreateRoute,
} as any)
const EditorProjectIdEditorItemsItemUidCreateChargesRoute = EditorProjectIdEditorItemsItemUidCreateChargesRouteImport.update({
  id: "/charges",
  path: "/charges",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidCreateRoute,
} as any)
const EditorProjectIdEditorItemsItemUidCreateMergesRoute = EditorProjectIdEditorItemsItemUidCreateMergesRouteImport.update({
  id: "/merges",
  path: "/merges",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidCreateRoute,
} as any)
const EditorProjectIdEditorItemsItemUidCreateProductionRoute = EditorProjectIdEditorItemsItemUidCreateProductionRouteImport.update({
  id: "/production",
  path: "/production",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidCreateRoute,
} as any)
const EditorProjectIdEditorItemsItemUidEditIndexRoute = EditorProjectIdEditorItemsItemUidEditIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidEditRoute,
} as any)
const EditorProjectIdEditorItemsItemUidEditIdentityRoute = EditorProjectIdEditorItemsItemUidEditIdentityRouteImport.update({
  id: "/identity",
  path: "/identity",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidEditRoute,
} as any)
const EditorProjectIdEditorItemsItemUidEditArtworkRoute = EditorProjectIdEditorItemsItemUidEditArtworkRouteImport.update({
  id: "/artwork",
  path: "/artwork",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidEditRoute,
} as any)
const EditorProjectIdEditorItemsItemUidEditLimitsRoute = EditorProjectIdEditorItemsItemUidEditLimitsRouteImport.update({
  id: "/limits",
  path: "/limits",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidEditRoute,
} as any)
const EditorProjectIdEditorItemsItemUidEditChargesRoute = EditorProjectIdEditorItemsItemUidEditChargesRouteImport.update({
  id: "/charges",
  path: "/charges",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidEditRoute,
} as any)
const EditorProjectIdEditorItemsItemUidEditMergesRoute = EditorProjectIdEditorItemsItemUidEditMergesRouteImport.update({
  id: "/merges",
  path: "/merges",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidEditRoute,
} as any)
const EditorProjectIdEditorItemsItemUidEditProductionRoute = EditorProjectIdEditorItemsItemUidEditProductionRouteImport.update({
  id: "/production",
  path: "/production",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidEditRoute,
} as any)
const EditorProjectIdEditorItemsItemUidViewRoute = EditorProjectIdEditorItemsItemUidViewRouteImport.update({
  id: "/view",
  path: "/view",
  getParentRoute: () => EditorProjectIdEditorItemsItemUidRoute,
} as any)
const EditorProjectIdEditorItemsNewRoute = EditorProjectIdEditorItemsNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => EditorProjectIdEditorItemsRoute,
} as any)
const EditorProjectIdEditorItemsNewSelectRoute = EditorProjectIdEditorItemsNewSelectRouteImport.update({
  id: "/select",
  path: "/select",
  getParentRoute: () => EditorProjectIdEditorItemsNewRoute,
} as any)

export interface FileRoutesByFullPath {
  "/editor": typeof EditorRouteWithChildren
  "/": typeof IndexRoute
  "/game/$packageId": typeof GamePackageIdRouteWithChildren
  "/editor/welcome": typeof EditorWelcomeRoute
  "/editor/$projectId": typeof EditorProjectIdRouteWithChildren
  "/action/recover-game-save": typeof ActionRecoverGameSaveRoute
  "/action/discard-failed-game": typeof ActionDiscardFailedGameRoute
  "/settings": typeof LauncherSettingsRoute
  "/main-menu": typeof LauncherMainMenuRoute
  "/arkpacks": typeof LauncherArkpacksRoute
  "/about": typeof LauncherAboutRoute
  "/game/$packageId/cheats": typeof GamePackageIdCheatsRoute
  "/editor/$projectId/project": typeof EditorProjectIdProjectRoute
  "/editor/$projectId/editor": typeof EditorProjectIdEditorRouteWithChildren
  "/editor/$projectId/build": typeof EditorProjectIdBuildRoute
  "/editor/$projectId/board": typeof EditorProjectIdBoardRoute
  "/editor/$projectId/assets": typeof EditorProjectIdAssetsRoute
  "/action/load-game/$packageId": typeof ActionLoadGamePackageIdRoute
  "/editor/$projectId/editor/": typeof EditorProjectIdEditorIndexRoute
  "/game/$packageId/action/reset": typeof GamePackageIdActionResetRoute
  "/game/$packageId/action/leave": typeof GamePackageIdActionLeaveRoute
  "/game/$packageId/action/exit": typeof GamePackageIdActionExitRoute
  "/game/$packageId/inventory": typeof GamePackageIdSceneInventoryRoute
  "/game/$packageId/board": typeof GamePackageIdSceneBoardRoute
  "/editor/$projectId/editor/items": typeof EditorProjectIdEditorItemsRouteWithChildren
  "/editor/$projectId/editor/items/list": typeof EditorProjectIdEditorItemsListRoute
  "/editor/$projectId/editor/items/$itemUid": typeof EditorProjectIdEditorItemsItemUidRouteWithChildren
  "/editor/$projectId/editor/items/$itemUid/create": typeof EditorProjectIdEditorItemsItemUidCreateRouteWithChildren
  "/editor/$projectId/editor/items/$itemUid/edit": typeof EditorProjectIdEditorItemsItemUidEditRouteWithChildren
  "/editor/$projectId/editor/items/$itemUid/create/": typeof EditorProjectIdEditorItemsItemUidCreateIndexRoute
  "/editor/$projectId/editor/items/$itemUid/create/identity": typeof EditorProjectIdEditorItemsItemUidCreateIdentityRoute
  "/editor/$projectId/editor/items/$itemUid/create/artwork": typeof EditorProjectIdEditorItemsItemUidCreateArtworkRoute
  "/editor/$projectId/editor/items/$itemUid/create/limits": typeof EditorProjectIdEditorItemsItemUidCreateLimitsRoute
  "/editor/$projectId/editor/items/$itemUid/create/charges": typeof EditorProjectIdEditorItemsItemUidCreateChargesRoute
  "/editor/$projectId/editor/items/$itemUid/create/merges": typeof EditorProjectIdEditorItemsItemUidCreateMergesRoute
  "/editor/$projectId/editor/items/$itemUid/create/production": typeof EditorProjectIdEditorItemsItemUidCreateProductionRoute
  "/editor/$projectId/editor/items/$itemUid/edit/": typeof EditorProjectIdEditorItemsItemUidEditIndexRoute
  "/editor/$projectId/editor/items/$itemUid/edit/identity": typeof EditorProjectIdEditorItemsItemUidEditIdentityRoute
  "/editor/$projectId/editor/items/$itemUid/edit/artwork": typeof EditorProjectIdEditorItemsItemUidEditArtworkRoute
  "/editor/$projectId/editor/items/$itemUid/edit/limits": typeof EditorProjectIdEditorItemsItemUidEditLimitsRoute
  "/editor/$projectId/editor/items/$itemUid/edit/charges": typeof EditorProjectIdEditorItemsItemUidEditChargesRoute
  "/editor/$projectId/editor/items/$itemUid/edit/merges": typeof EditorProjectIdEditorItemsItemUidEditMergesRoute
  "/editor/$projectId/editor/items/$itemUid/edit/production": typeof EditorProjectIdEditorItemsItemUidEditProductionRoute
  "/editor/$projectId/editor/items/$itemUid/view": typeof EditorProjectIdEditorItemsItemUidViewRoute
  "/editor/$projectId/editor/items/new": typeof EditorProjectIdEditorItemsNewRouteWithChildren
  "/editor/$projectId/editor/items/new/select": typeof EditorProjectIdEditorItemsNewSelectRoute
}
export interface FileRoutesByTo {
  "/editor": typeof EditorRouteWithChildren
  "/": typeof IndexRoute
  "/game/$packageId": typeof GamePackageIdRouteWithChildren
  "/editor/welcome": typeof EditorWelcomeRoute
  "/editor/$projectId": typeof EditorProjectIdRouteWithChildren
  "/action/recover-game-save": typeof ActionRecoverGameSaveRoute
  "/action/discard-failed-game": typeof ActionDiscardFailedGameRoute
  "/settings": typeof LauncherSettingsRoute
  "/main-menu": typeof LauncherMainMenuRoute
  "/arkpacks": typeof LauncherArkpacksRoute
  "/about": typeof LauncherAboutRoute
  "/game/$packageId/cheats": typeof GamePackageIdCheatsRoute
  "/editor/$projectId/project": typeof EditorProjectIdProjectRoute
  "/editor/$projectId/build": typeof EditorProjectIdBuildRoute
  "/editor/$projectId/board": typeof EditorProjectIdBoardRoute
  "/editor/$projectId/assets": typeof EditorProjectIdAssetsRoute
  "/action/load-game/$packageId": typeof ActionLoadGamePackageIdRoute
  "/editor/$projectId/editor": typeof EditorProjectIdEditorIndexRoute
  "/game/$packageId/action/reset": typeof GamePackageIdActionResetRoute
  "/game/$packageId/action/leave": typeof GamePackageIdActionLeaveRoute
  "/game/$packageId/action/exit": typeof GamePackageIdActionExitRoute
  "/game/$packageId/inventory": typeof GamePackageIdSceneInventoryRoute
  "/game/$packageId/board": typeof GamePackageIdSceneBoardRoute
  "/editor/$projectId/editor/items": typeof EditorProjectIdEditorItemsRouteWithChildren
  "/editor/$projectId/editor/items/list": typeof EditorProjectIdEditorItemsListRoute
  "/editor/$projectId/editor/items/$itemUid": typeof EditorProjectIdEditorItemsItemUidRouteWithChildren
  "/editor/$projectId/editor/items/$itemUid/create": typeof EditorProjectIdEditorItemsItemUidCreateIndexRoute
  "/editor/$projectId/editor/items/$itemUid/edit": typeof EditorProjectIdEditorItemsItemUidEditIndexRoute
  "/editor/$projectId/editor/items/$itemUid/create/identity": typeof EditorProjectIdEditorItemsItemUidCreateIdentityRoute
  "/editor/$projectId/editor/items/$itemUid/create/artwork": typeof EditorProjectIdEditorItemsItemUidCreateArtworkRoute
  "/editor/$projectId/editor/items/$itemUid/create/limits": typeof EditorProjectIdEditorItemsItemUidCreateLimitsRoute
  "/editor/$projectId/editor/items/$itemUid/create/charges": typeof EditorProjectIdEditorItemsItemUidCreateChargesRoute
  "/editor/$projectId/editor/items/$itemUid/create/merges": typeof EditorProjectIdEditorItemsItemUidCreateMergesRoute
  "/editor/$projectId/editor/items/$itemUid/create/production": typeof EditorProjectIdEditorItemsItemUidCreateProductionRoute
  "/editor/$projectId/editor/items/$itemUid/edit/identity": typeof EditorProjectIdEditorItemsItemUidEditIdentityRoute
  "/editor/$projectId/editor/items/$itemUid/edit/artwork": typeof EditorProjectIdEditorItemsItemUidEditArtworkRoute
  "/editor/$projectId/editor/items/$itemUid/edit/limits": typeof EditorProjectIdEditorItemsItemUidEditLimitsRoute
  "/editor/$projectId/editor/items/$itemUid/edit/charges": typeof EditorProjectIdEditorItemsItemUidEditChargesRoute
  "/editor/$projectId/editor/items/$itemUid/edit/merges": typeof EditorProjectIdEditorItemsItemUidEditMergesRoute
  "/editor/$projectId/editor/items/$itemUid/edit/production": typeof EditorProjectIdEditorItemsItemUidEditProductionRoute
  "/editor/$projectId/editor/items/$itemUid/view": typeof EditorProjectIdEditorItemsItemUidViewRoute
  "/editor/$projectId/editor/items/new": typeof EditorProjectIdEditorItemsNewRouteWithChildren
  "/editor/$projectId/editor/items/new/select": typeof EditorProjectIdEditorItemsNewSelectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/editor": typeof EditorRouteWithChildren
  "/_launcher": typeof LauncherRouteWithChildren
  "/": typeof IndexRoute
  "/game/$packageId": typeof GamePackageIdRouteWithChildren
  "/editor/welcome": typeof EditorWelcomeRoute
  "/editor/$projectId": typeof EditorProjectIdRouteWithChildren
  "/action/recover-game-save": typeof ActionRecoverGameSaveRoute
  "/action/discard-failed-game": typeof ActionDiscardFailedGameRoute
  "/_launcher/settings": typeof LauncherSettingsRoute
  "/_launcher/main-menu": typeof LauncherMainMenuRoute
  "/_launcher/arkpacks": typeof LauncherArkpacksRoute
  "/_launcher/about": typeof LauncherAboutRoute
  "/game/$packageId/cheats": typeof GamePackageIdCheatsRoute
  "/game/$packageId/_scene": typeof GamePackageIdSceneRouteWithChildren
  "/editor/$projectId/project": typeof EditorProjectIdProjectRoute
  "/editor/$projectId/editor": typeof EditorProjectIdEditorRouteWithChildren
  "/editor/$projectId/build": typeof EditorProjectIdBuildRoute
  "/editor/$projectId/board": typeof EditorProjectIdBoardRoute
  "/editor/$projectId/assets": typeof EditorProjectIdAssetsRoute
  "/action/load-game/$packageId": typeof ActionLoadGamePackageIdRoute
  "/editor/$projectId/editor/": typeof EditorProjectIdEditorIndexRoute
  "/game/$packageId/action/reset": typeof GamePackageIdActionResetRoute
  "/game/$packageId/action/leave": typeof GamePackageIdActionLeaveRoute
  "/game/$packageId/action/exit": typeof GamePackageIdActionExitRoute
  "/game/$packageId/_scene/inventory": typeof GamePackageIdSceneInventoryRoute
  "/game/$packageId/_scene/board": typeof GamePackageIdSceneBoardRoute
  "/editor/$projectId/editor/items": typeof EditorProjectIdEditorItemsRouteWithChildren
  "/editor/$projectId/editor/items/list": typeof EditorProjectIdEditorItemsListRoute
  "/editor/$projectId/editor/items/$itemUid": typeof EditorProjectIdEditorItemsItemUidRouteWithChildren
  "/editor/$projectId/editor/items/$itemUid/create": typeof EditorProjectIdEditorItemsItemUidCreateRouteWithChildren
  "/editor/$projectId/editor/items/$itemUid/edit": typeof EditorProjectIdEditorItemsItemUidEditRouteWithChildren
  "/editor/$projectId/editor/items/$itemUid/create/": typeof EditorProjectIdEditorItemsItemUidCreateIndexRoute
  "/editor/$projectId/editor/items/$itemUid/create/identity": typeof EditorProjectIdEditorItemsItemUidCreateIdentityRoute
  "/editor/$projectId/editor/items/$itemUid/create/artwork": typeof EditorProjectIdEditorItemsItemUidCreateArtworkRoute
  "/editor/$projectId/editor/items/$itemUid/create/limits": typeof EditorProjectIdEditorItemsItemUidCreateLimitsRoute
  "/editor/$projectId/editor/items/$itemUid/create/charges": typeof EditorProjectIdEditorItemsItemUidCreateChargesRoute
  "/editor/$projectId/editor/items/$itemUid/create/merges": typeof EditorProjectIdEditorItemsItemUidCreateMergesRoute
  "/editor/$projectId/editor/items/$itemUid/create/production": typeof EditorProjectIdEditorItemsItemUidCreateProductionRoute
  "/editor/$projectId/editor/items/$itemUid/edit/": typeof EditorProjectIdEditorItemsItemUidEditIndexRoute
  "/editor/$projectId/editor/items/$itemUid/edit/identity": typeof EditorProjectIdEditorItemsItemUidEditIdentityRoute
  "/editor/$projectId/editor/items/$itemUid/edit/artwork": typeof EditorProjectIdEditorItemsItemUidEditArtworkRoute
  "/editor/$projectId/editor/items/$itemUid/edit/limits": typeof EditorProjectIdEditorItemsItemUidEditLimitsRoute
  "/editor/$projectId/editor/items/$itemUid/edit/charges": typeof EditorProjectIdEditorItemsItemUidEditChargesRoute
  "/editor/$projectId/editor/items/$itemUid/edit/merges": typeof EditorProjectIdEditorItemsItemUidEditMergesRoute
  "/editor/$projectId/editor/items/$itemUid/edit/production": typeof EditorProjectIdEditorItemsItemUidEditProductionRoute
  "/editor/$projectId/editor/items/$itemUid/view": typeof EditorProjectIdEditorItemsItemUidViewRoute
  "/editor/$projectId/editor/items/new": typeof EditorProjectIdEditorItemsNewRouteWithChildren
  "/editor/$projectId/editor/items/new/select": typeof EditorProjectIdEditorItemsNewSelectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/editor"
    | "/"
    | "/game/$packageId"
    | "/editor/welcome"
    | "/editor/$projectId"
    | "/action/recover-game-save"
    | "/action/discard-failed-game"
    | "/settings"
    | "/main-menu"
    | "/arkpacks"
    | "/about"
    | "/game/$packageId/cheats"
    | "/editor/$projectId/project"
    | "/editor/$projectId/editor"
    | "/editor/$projectId/build"
    | "/editor/$projectId/board"
    | "/editor/$projectId/assets"
    | "/action/load-game/$packageId"
    | "/editor/$projectId/editor/"
    | "/game/$packageId/action/reset"
    | "/game/$packageId/action/leave"
    | "/game/$packageId/action/exit"
    | "/game/$packageId/inventory"
    | "/game/$packageId/board"
    | "/editor/$projectId/editor/items"
    | "/editor/$projectId/editor/items/list"
    | "/editor/$projectId/editor/items/$itemUid"
    | "/editor/$projectId/editor/items/$itemUid/create"
    | "/editor/$projectId/editor/items/$itemUid/edit"
    | "/editor/$projectId/editor/items/$itemUid/create/"
    | "/editor/$projectId/editor/items/$itemUid/create/identity"
    | "/editor/$projectId/editor/items/$itemUid/create/artwork"
    | "/editor/$projectId/editor/items/$itemUid/create/limits"
    | "/editor/$projectId/editor/items/$itemUid/create/charges"
    | "/editor/$projectId/editor/items/$itemUid/create/merges"
    | "/editor/$projectId/editor/items/$itemUid/create/production"
    | "/editor/$projectId/editor/items/$itemUid/edit/"
    | "/editor/$projectId/editor/items/$itemUid/edit/identity"
    | "/editor/$projectId/editor/items/$itemUid/edit/artwork"
    | "/editor/$projectId/editor/items/$itemUid/edit/limits"
    | "/editor/$projectId/editor/items/$itemUid/edit/charges"
    | "/editor/$projectId/editor/items/$itemUid/edit/merges"
    | "/editor/$projectId/editor/items/$itemUid/edit/production"
    | "/editor/$projectId/editor/items/$itemUid/view"
    | "/editor/$projectId/editor/items/new"
    | "/editor/$projectId/editor/items/new/select"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/editor"
    | "/"
    | "/game/$packageId"
    | "/editor/welcome"
    | "/editor/$projectId"
    | "/action/recover-game-save"
    | "/action/discard-failed-game"
    | "/settings"
    | "/main-menu"
    | "/arkpacks"
    | "/about"
    | "/game/$packageId/cheats"
    | "/editor/$projectId/project"
    | "/editor/$projectId/build"
    | "/editor/$projectId/board"
    | "/editor/$projectId/assets"
    | "/action/load-game/$packageId"
    | "/editor/$projectId/editor"
    | "/game/$packageId/action/reset"
    | "/game/$packageId/action/leave"
    | "/game/$packageId/action/exit"
    | "/game/$packageId/inventory"
    | "/game/$packageId/board"
    | "/editor/$projectId/editor/items"
    | "/editor/$projectId/editor/items/list"
    | "/editor/$projectId/editor/items/$itemUid"
    | "/editor/$projectId/editor/items/$itemUid/create"
    | "/editor/$projectId/editor/items/$itemUid/edit"
    | "/editor/$projectId/editor/items/$itemUid/create/identity"
    | "/editor/$projectId/editor/items/$itemUid/create/artwork"
    | "/editor/$projectId/editor/items/$itemUid/create/limits"
    | "/editor/$projectId/editor/items/$itemUid/create/charges"
    | "/editor/$projectId/editor/items/$itemUid/create/merges"
    | "/editor/$projectId/editor/items/$itemUid/create/production"
    | "/editor/$projectId/editor/items/$itemUid/edit/identity"
    | "/editor/$projectId/editor/items/$itemUid/edit/artwork"
    | "/editor/$projectId/editor/items/$itemUid/edit/limits"
    | "/editor/$projectId/editor/items/$itemUid/edit/charges"
    | "/editor/$projectId/editor/items/$itemUid/edit/merges"
    | "/editor/$projectId/editor/items/$itemUid/edit/production"
    | "/editor/$projectId/editor/items/$itemUid/view"
    | "/editor/$projectId/editor/items/new"
    | "/editor/$projectId/editor/items/new/select"
  id:
    | "__root__"
    | "/editor"
    | "/_launcher"
    | "/"
    | "/game/$packageId"
    | "/editor/welcome"
    | "/editor/$projectId"
    | "/action/recover-game-save"
    | "/action/discard-failed-game"
    | "/_launcher/settings"
    | "/_launcher/main-menu"
    | "/_launcher/arkpacks"
    | "/_launcher/about"
    | "/game/$packageId/cheats"
    | "/game/$packageId/_scene"
    | "/editor/$projectId/project"
    | "/editor/$projectId/editor"
    | "/editor/$projectId/build"
    | "/editor/$projectId/board"
    | "/editor/$projectId/assets"
    | "/action/load-game/$packageId"
    | "/editor/$projectId/editor/"
    | "/game/$packageId/action/reset"
    | "/game/$packageId/action/leave"
    | "/game/$packageId/action/exit"
    | "/game/$packageId/_scene/inventory"
    | "/game/$packageId/_scene/board"
    | "/editor/$projectId/editor/items"
    | "/editor/$projectId/editor/items/list"
    | "/editor/$projectId/editor/items/$itemUid"
    | "/editor/$projectId/editor/items/$itemUid/create"
    | "/editor/$projectId/editor/items/$itemUid/edit"
    | "/editor/$projectId/editor/items/$itemUid/create/"
    | "/editor/$projectId/editor/items/$itemUid/create/identity"
    | "/editor/$projectId/editor/items/$itemUid/create/artwork"
    | "/editor/$projectId/editor/items/$itemUid/create/limits"
    | "/editor/$projectId/editor/items/$itemUid/create/charges"
    | "/editor/$projectId/editor/items/$itemUid/create/merges"
    | "/editor/$projectId/editor/items/$itemUid/create/production"
    | "/editor/$projectId/editor/items/$itemUid/edit/"
    | "/editor/$projectId/editor/items/$itemUid/edit/identity"
    | "/editor/$projectId/editor/items/$itemUid/edit/artwork"
    | "/editor/$projectId/editor/items/$itemUid/edit/limits"
    | "/editor/$projectId/editor/items/$itemUid/edit/charges"
    | "/editor/$projectId/editor/items/$itemUid/edit/merges"
    | "/editor/$projectId/editor/items/$itemUid/edit/production"
    | "/editor/$projectId/editor/items/$itemUid/view"
    | "/editor/$projectId/editor/items/new"
    | "/editor/$projectId/editor/items/new/select"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EditorRoute: typeof EditorRouteWithChildren
  LauncherRoute: typeof LauncherRouteWithChildren
  IndexRoute: typeof IndexRoute
  GamePackageIdRoute: typeof GamePackageIdRouteWithChildren
  ActionRecoverGameSaveRoute: typeof ActionRecoverGameSaveRoute
  ActionDiscardFailedGameRoute: typeof ActionDiscardFailedGameRoute
  ActionLoadGamePackageIdRoute: typeof ActionLoadGamePackageIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/editor": {
      id: "/editor"
      path: "/editor"
      fullPath: "/editor"
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_launcher": {
      id: "/_launcher"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof LauncherRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/game/$packageId": {
      id: "/game/$packageId"
      path: "/game/$packageId"
      fullPath: "/game/$packageId"
      preLoaderRoute: typeof GamePackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/editor/welcome": {
      id: "/editor/welcome"
      path: "/welcome"
      fullPath: "/editor/welcome"
      preLoaderRoute: typeof EditorWelcomeRouteImport
      parentRoute: typeof EditorRoute
    }
    "/editor/$projectId": {
      id: "/editor/$projectId"
      path: "/$projectId"
      fullPath: "/editor/$projectId"
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof EditorRoute
    }
    "/action/recover-game-save": {
      id: "/action/recover-game-save"
      path: "/action/recover-game-save"
      fullPath: "/action/recover-game-save"
      preLoaderRoute: typeof ActionRecoverGameSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/action/discard-failed-game": {
      id: "/action/discard-failed-game"
      path: "/action/discard-failed-game"
      fullPath: "/action/discard-failed-game"
      preLoaderRoute: typeof ActionDiscardFailedGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_launcher/settings": {
      id: "/_launcher/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof LauncherSettingsRouteImport
      parentRoute: typeof LauncherRoute
    }
    "/_launcher/main-menu": {
      id: "/_launcher/main-menu"
      path: "/main-menu"
      fullPath: "/main-menu"
      preLoaderRoute: typeof LauncherMainMenuRouteImport
      parentRoute: typeof LauncherRoute
    }
    "/_launcher/arkpacks": {
      id: "/_launcher/arkpacks"
      path: "/arkpacks"
      fullPath: "/arkpacks"
      preLoaderRoute: typeof LauncherArkpacksRouteImport
      parentRoute: typeof LauncherRoute
    }
    "/_launcher/about": {
      id: "/_launcher/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof LauncherAboutRouteImport
      parentRoute: typeof LauncherRoute
    }
    "/game/$packageId/cheats": {
      id: "/game/$packageId/cheats"
      path: "/cheats"
      fullPath: "/game/$packageId/cheats"
      preLoaderRoute: typeof GamePackageIdCheatsRouteImport
      parentRoute: typeof GamePackageIdRoute
    }
    "/game/$packageId/_scene": {
      id: "/game/$packageId/_scene"
      path: ""
      fullPath: "/game/$packageId"
      preLoaderRoute: typeof GamePackageIdSceneRouteImport
      parentRoute: typeof GamePackageIdRoute
    }
    "/editor/$projectId/project": {
      id: "/editor/$projectId/project"
      path: "/project"
      fullPath: "/editor/$projectId/project"
      preLoaderRoute: typeof EditorProjectIdProjectRouteImport
      parentRoute: typeof EditorProjectIdRoute
    }
    "/editor/$projectId/editor": {
      id: "/editor/$projectId/editor"
      path: "/editor"
      fullPath: "/editor/$projectId/editor"
      preLoaderRoute: typeof EditorProjectIdEditorRouteImport
      parentRoute: typeof EditorProjectIdRoute
    }
    "/editor/$projectId/build": {
      id: "/editor/$projectId/build"
      path: "/build"
      fullPath: "/editor/$projectId/build"
      preLoaderRoute: typeof EditorProjectIdBuildRouteImport
      parentRoute: typeof EditorProjectIdRoute
    }
    "/editor/$projectId/board": {
      id: "/editor/$projectId/board"
      path: "/board"
      fullPath: "/editor/$projectId/board"
      preLoaderRoute: typeof EditorProjectIdBoardRouteImport
      parentRoute: typeof EditorProjectIdRoute
    }
    "/editor/$projectId/assets": {
      id: "/editor/$projectId/assets"
      path: "/assets"
      fullPath: "/editor/$projectId/assets"
      preLoaderRoute: typeof EditorProjectIdAssetsRouteImport
      parentRoute: typeof EditorProjectIdRoute
    }
    "/action/load-game/$packageId": {
      id: "/action/load-game/$packageId"
      path: "/action/load-game/$packageId"
      fullPath: "/action/load-game/$packageId"
      preLoaderRoute: typeof ActionLoadGamePackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/editor/$projectId/editor/": {
      id: "/editor/$projectId/editor/"
      path: "/"
      fullPath: "/editor/$projectId/editor/"
      preLoaderRoute: typeof EditorProjectIdEditorIndexRouteImport
      parentRoute: typeof EditorProjectIdEditorRoute
    }
    "/game/$packageId/action/reset": {
      id: "/game/$packageId/action/reset"
      path: "/action/reset"
      fullPath: "/game/$packageId/action/reset"
      preLoaderRoute: typeof GamePackageIdActionResetRouteImport
      parentRoute: typeof GamePackageIdRoute
    }
    "/game/$packageId/action/leave": {
      id: "/game/$packageId/action/leave"
      path: "/action/leave"
      fullPath: "/game/$packageId/action/leave"
      preLoaderRoute: typeof GamePackageIdActionLeaveRouteImport
      parentRoute: typeof GamePackageIdRoute
    }
    "/game/$packageId/action/exit": {
      id: "/game/$packageId/action/exit"
      path: "/action/exit"
      fullPath: "/game/$packageId/action/exit"
      preLoaderRoute: typeof GamePackageIdActionExitRouteImport
      parentRoute: typeof GamePackageIdRoute
    }
    "/game/$packageId/_scene/inventory": {
      id: "/game/$packageId/_scene/inventory"
      path: "/inventory"
      fullPath: "/game/$packageId/inventory"
      preLoaderRoute: typeof GamePackageIdSceneInventoryRouteImport
      parentRoute: typeof GamePackageIdSceneRoute
    }
    "/game/$packageId/_scene/board": {
      id: "/game/$packageId/_scene/board"
      path: "/board"
      fullPath: "/game/$packageId/board"
      preLoaderRoute: typeof GamePackageIdSceneBoardRouteImport
      parentRoute: typeof GamePackageIdSceneRoute
    }
    "/editor/$projectId/editor/items": {
      id: "/editor/$projectId/editor/items"
      path: "/items"
      fullPath: "/editor/$projectId/editor/items"
      preLoaderRoute: typeof EditorProjectIdEditorItemsRouteImport
      parentRoute: typeof EditorProjectIdEditorRoute
    }
    "/editor/$projectId/editor/items/list": {
      id: "/editor/$projectId/editor/items/list"
      path: "/list"
      fullPath: "/editor/$projectId/editor/items/list"
      preLoaderRoute: typeof EditorProjectIdEditorItemsListRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsRoute
    }
    "/editor/$projectId/editor/items/$itemUid": {
      id: "/editor/$projectId/editor/items/$itemUid"
      path: "/$itemUid"
      fullPath: "/editor/$projectId/editor/items/$itemUid"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsRoute
    }
    "/editor/$projectId/editor/items/$itemUid/create": {
      id: "/editor/$projectId/editor/items/$itemUid/create"
      path: "/create"
      fullPath: "/editor/$projectId/editor/items/$itemUid/create"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidCreateRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidRoute
    }
    "/editor/$projectId/editor/items/$itemUid/edit": {
      id: "/editor/$projectId/editor/items/$itemUid/edit"
      path: "/edit"
      fullPath: "/editor/$projectId/editor/items/$itemUid/edit"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidEditRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidRoute
    }
    "/editor/$projectId/editor/items/$itemUid/create/": {
      id: "/editor/$projectId/editor/items/$itemUid/create/"
      path: "/"
      fullPath: "/editor/$projectId/editor/items/$itemUid/create/"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidCreateIndexRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidCreateRoute
    }
    "/editor/$projectId/editor/items/$itemUid/create/identity": {
      id: "/editor/$projectId/editor/items/$itemUid/create/identity"
      path: "/identity"
      fullPath: "/editor/$projectId/editor/items/$itemUid/create/identity"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidCreateIdentityRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidCreateRoute
    }
    "/editor/$projectId/editor/items/$itemUid/create/artwork": {
      id: "/editor/$projectId/editor/items/$itemUid/create/artwork"
      path: "/artwork"
      fullPath: "/editor/$projectId/editor/items/$itemUid/create/artwork"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidCreateArtworkRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidCreateRoute
    }
    "/editor/$projectId/editor/items/$itemUid/create/limits": {
      id: "/editor/$projectId/editor/items/$itemUid/create/limits"
      path: "/limits"
      fullPath: "/editor/$projectId/editor/items/$itemUid/create/limits"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidCreateLimitsRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidCreateRoute
    }
    "/editor/$projectId/editor/items/$itemUid/create/charges": {
      id: "/editor/$projectId/editor/items/$itemUid/create/charges"
      path: "/charges"
      fullPath: "/editor/$projectId/editor/items/$itemUid/create/charges"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidCreateChargesRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidCreateRoute
    }
    "/editor/$projectId/editor/items/$itemUid/create/merges": {
      id: "/editor/$projectId/editor/items/$itemUid/create/merges"
      path: "/merges"
      fullPath: "/editor/$projectId/editor/items/$itemUid/create/merges"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidCreateMergesRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidCreateRoute
    }
    "/editor/$projectId/editor/items/$itemUid/create/production": {
      id: "/editor/$projectId/editor/items/$itemUid/create/production"
      path: "/production"
      fullPath: "/editor/$projectId/editor/items/$itemUid/create/production"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidCreateProductionRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidCreateRoute
    }
    "/editor/$projectId/editor/items/$itemUid/edit/": {
      id: "/editor/$projectId/editor/items/$itemUid/edit/"
      path: "/"
      fullPath: "/editor/$projectId/editor/items/$itemUid/edit/"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidEditIndexRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidEditRoute
    }
    "/editor/$projectId/editor/items/$itemUid/edit/identity": {
      id: "/editor/$projectId/editor/items/$itemUid/edit/identity"
      path: "/identity"
      fullPath: "/editor/$projectId/editor/items/$itemUid/edit/identity"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidEditIdentityRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidEditRoute
    }
    "/editor/$projectId/editor/items/$itemUid/edit/artwork": {
      id: "/editor/$projectId/editor/items/$itemUid/edit/artwork"
      path: "/artwork"
      fullPath: "/editor/$projectId/editor/items/$itemUid/edit/artwork"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidEditArtworkRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidEditRoute
    }
    "/editor/$projectId/editor/items/$itemUid/edit/limits": {
      id: "/editor/$projectId/editor/items/$itemUid/edit/limits"
      path: "/limits"
      fullPath: "/editor/$projectId/editor/items/$itemUid/edit/limits"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidEditLimitsRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidEditRoute
    }
    "/editor/$projectId/editor/items/$itemUid/edit/charges": {
      id: "/editor/$projectId/editor/items/$itemUid/edit/charges"
      path: "/charges"
      fullPath: "/editor/$projectId/editor/items/$itemUid/edit/charges"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidEditChargesRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidEditRoute
    }
    "/editor/$projectId/editor/items/$itemUid/edit/merges": {
      id: "/editor/$projectId/editor/items/$itemUid/edit/merges"
      path: "/merges"
      fullPath: "/editor/$projectId/editor/items/$itemUid/edit/merges"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidEditMergesRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidEditRoute
    }
    "/editor/$projectId/editor/items/$itemUid/edit/production": {
      id: "/editor/$projectId/editor/items/$itemUid/edit/production"
      path: "/production"
      fullPath: "/editor/$projectId/editor/items/$itemUid/edit/production"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidEditProductionRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidEditRoute
    }
    "/editor/$projectId/editor/items/$itemUid/view": {
      id: "/editor/$projectId/editor/items/$itemUid/view"
      path: "/view"
      fullPath: "/editor/$projectId/editor/items/$itemUid/view"
      preLoaderRoute: typeof EditorProjectIdEditorItemsItemUidViewRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsItemUidRoute
    }
    "/editor/$projectId/editor/items/new": {
      id: "/editor/$projectId/editor/items/new"
      path: "/new"
      fullPath: "/editor/$projectId/editor/items/new"
      preLoaderRoute: typeof EditorProjectIdEditorItemsNewRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsRoute
    }
    "/editor/$projectId/editor/items/new/select": {
      id: "/editor/$projectId/editor/items/new/select"
      path: "/select"
      fullPath: "/editor/$projectId/editor/items/new/select"
      preLoaderRoute: typeof EditorProjectIdEditorItemsNewSelectRouteImport
      parentRoute: typeof EditorProjectIdEditorItemsNewRoute
    }
  }
}

interface EditorProjectIdEditorItemsItemUidCreateRouteChildren {
  EditorProjectIdEditorItemsItemUidCreateIndexRoute: typeof EditorProjectIdEditorItemsItemUidCreateIndexRoute
  EditorProjectIdEditorItemsItemUidCreateIdentityRoute: typeof EditorProjectIdEditorItemsItemUidCreateIdentityRoute
  EditorProjectIdEditorItemsItemUidCreateArtworkRoute: typeof EditorProjectIdEditorItemsItemUidCreateArtworkRoute
  EditorProjectIdEditorItemsItemUidCreateLimitsRoute: typeof EditorProjectIdEditorItemsItemUidCreateLimitsRoute
  EditorProjectIdEditorItemsItemUidCreateChargesRoute: typeof EditorProjectIdEditorItemsItemUidCreateChargesRoute
  EditorProjectIdEditorItemsItemUidCreateMergesRoute: typeof EditorProjectIdEditorItemsItemUidCreateMergesRoute
  EditorProjectIdEditorItemsItemUidCreateProductionRoute: typeof EditorProjectIdEditorItemsItemUidCreateProductionRoute
}

const EditorProjectIdEditorItemsItemUidCreateRouteChildren: EditorProjectIdEditorItemsItemUidCreateRouteChildren = {
  EditorProjectIdEditorItemsItemUidCreateIndexRoute: EditorProjectIdEditorItemsItemUidCreateIndexRoute,
  EditorProjectIdEditorItemsItemUidCreateIdentityRoute: EditorProjectIdEditorItemsItemUidCreateIdentityRoute,
  EditorProjectIdEditorItemsItemUidCreateArtworkRoute: EditorProjectIdEditorItemsItemUidCreateArtworkRoute,
  EditorProjectIdEditorItemsItemUidCreateLimitsRoute: EditorProjectIdEditorItemsItemUidCreateLimitsRoute,
  EditorProjectIdEditorItemsItemUidCreateChargesRoute: EditorProjectIdEditorItemsItemUidCreateChargesRoute,
  EditorProjectIdEditorItemsItemUidCreateMergesRoute: EditorProjectIdEditorItemsItemUidCreateMergesRoute,
  EditorProjectIdEditorItemsItemUidCreateProductionRoute: EditorProjectIdEditorItemsItemUidCreateProductionRoute,
}

const EditorProjectIdEditorItemsItemUidCreateRouteWithChildren = EditorProjectIdEditorItemsItemUidCreateRoute._addFileChildren(
  EditorProjectIdEditorItemsItemUidCreateRouteChildren,
)

interface EditorProjectIdEditorItemsItemUidEditRouteChildren {
  EditorProjectIdEditorItemsItemUidEditIndexRoute: typeof EditorProjectIdEditorItemsItemUidEditIndexRoute
  EditorProjectIdEditorItemsItemUidEditIdentityRoute: typeof EditorProjectIdEditorItemsItemUidEditIdentityRoute
  EditorProjectIdEditorItemsItemUidEditArtworkRoute: typeof EditorProjectIdEditorItemsItemUidEditArtworkRoute
  EditorProjectIdEditorItemsItemUidEditLimitsRoute: typeof EditorProjectIdEditorItemsItemUidEditLimitsRoute
  EditorProjectIdEditorItemsItemUidEditChargesRoute: typeof EditorProjectIdEditorItemsItemUidEditChargesRoute
  EditorProjectIdEditorItemsItemUidEditMergesRoute: typeof EditorProjectIdEditorItemsItemUidEditMergesRoute
  EditorProjectIdEditorItemsItemUidEditProductionRoute: typeof EditorProjectIdEditorItemsItemUidEditProductionRoute
}

const EditorProjectIdEditorItemsItemUidEditRouteChildren: EditorProjectIdEditorItemsItemUidEditRouteChildren = {
  EditorProjectIdEditorItemsItemUidEditIndexRoute: EditorProjectIdEditorItemsItemUidEditIndexRoute,
  EditorProjectIdEditorItemsItemUidEditIdentityRoute: EditorProjectIdEditorItemsItemUidEditIdentityRoute,
  EditorProjectIdEditorItemsItemUidEditArtworkRoute: EditorProjectIdEditorItemsItemUidEditArtworkRoute,
  EditorProjectIdEditorItemsItemUidEditLimitsRoute: EditorProjectIdEditorItemsItemUidEditLimitsRoute,
  EditorProjectIdEditorItemsItemUidEditChargesRoute: EditorProjectIdEditorItemsItemUidEditChargesRoute,
  EditorProjectIdEditorItemsItemUidEditMergesRoute: EditorProjectIdEditorItemsItemUidEditMergesRoute,
  EditorProjectIdEditorItemsItemUidEditProductionRoute: EditorProjectIdEditorItemsItemUidEditProductionRoute,
}

const EditorProjectIdEditorItemsItemUidEditRouteWithChildren = EditorProjectIdEditorItemsItemUidEditRoute._addFileChildren(
  EditorProjectIdEditorItemsItemUidEditRouteChildren,
)

interface EditorProjectIdEditorItemsItemUidRouteChildren {
  EditorProjectIdEditorItemsItemUidCreateRoute: typeof EditorProjectIdEditorItemsItemUidCreateRouteWithChildren
  EditorProjectIdEditorItemsItemUidEditRoute: typeof EditorProjectIdEditorItemsItemUidEditRouteWithChildren
  EditorProjectIdEditorItemsItemUidViewRoute: typeof EditorProjectIdEditorItemsItemUidViewRoute
}

const EditorProjectIdEditorItemsItemUidRouteChildren: EditorProjectIdEditorItemsItemUidRouteChildren = {
  EditorProjectIdEditorItemsItemUidCreateRoute: EditorProjectIdEditorItemsItemUidCreateRouteWithChildren,
  EditorProjectIdEditorItemsItemUidEditRoute: EditorProjectIdEditorItemsItemUidEditRouteWithChildren,
  EditorProjectIdEditorItemsItemUidViewRoute: EditorProjectIdEditorItemsItemUidViewRoute,
}

const EditorProjectIdEditorItemsItemUidRouteWithChildren = EditorProjectIdEditorItemsItemUidRoute._addFileChildren(
  EditorProjectIdEditorItemsItemUidRouteChildren,
)

interface EditorProjectIdEditorItemsNewRouteChildren {
  EditorProjectIdEditorItemsNewSelectRoute: typeof EditorProjectIdEditorItemsNewSelectRoute
}

const EditorProjectIdEditorItemsNewRouteChildren: EditorProjectIdEditorItemsNewRouteChildren = {
  EditorProjectIdEditorItemsNewSelectRoute: EditorProjectIdEditorItemsNewSelectRoute,
}

const EditorProjectIdEditorItemsNewRouteWithChildren = EditorProjectIdEditorItemsNewRoute._addFileChildren(
  EditorProjectIdEditorItemsNewRouteChildren,
)

interface EditorProjectIdEditorItemsRouteChildren {
  EditorProjectIdEditorItemsListRoute: typeof EditorProjectIdEditorItemsListRoute
  EditorProjectIdEditorItemsItemUidRoute: typeof EditorProjectIdEditorItemsItemUidRouteWithChildren
  EditorProjectIdEditorItemsNewRoute: typeof EditorProjectIdEditorItemsNewRouteWithChildren
}

const EditorProjectIdEditorItemsRouteChildren: EditorProjectIdEditorItemsRouteChildren = {
  EditorProjectIdEditorItemsListRoute: EditorProjectIdEditorItemsListRoute,
  EditorProjectIdEditorItemsItemUidRoute: EditorProjectIdEditorItemsItemUidRouteWithChildren,
  EditorProjectIdEditorItemsNewRoute: EditorProjectIdEditorItemsNewRouteWithChildren,
}

const EditorProjectIdEditorItemsRouteWithChildren = EditorProjectIdEditorItemsRoute._addFileChildren(
  EditorProjectIdEditorItemsRouteChildren,
)

interface EditorProjectIdEditorRouteChildren {
  EditorProjectIdEditorIndexRoute: typeof EditorProjectIdEditorIndexRoute
  EditorProjectIdEditorItemsRoute: typeof EditorProjectIdEditorItemsRouteWithChildren
}

const EditorProjectIdEditorRouteChildren: EditorProjectIdEditorRouteChildren = {
  EditorProjectIdEditorIndexRoute: EditorProjectIdEditorIndexRoute,
  EditorProjectIdEditorItemsRoute: EditorProjectIdEditorItemsRouteWithChildren,
}

const EditorProjectIdEditorRouteWithChildren = EditorProjectIdEditorRoute._addFileChildren(
  EditorProjectIdEditorRouteChildren,
)

interface EditorProjectIdRouteChildren {
  EditorProjectIdProjectRoute: typeof EditorProjectIdProjectRoute
  EditorProjectIdEditorRoute: typeof EditorProjectIdEditorRouteWithChildren
  EditorProjectIdBuildRoute: typeof EditorProjectIdBuildRoute
  EditorProjectIdBoardRoute: typeof EditorProjectIdBoardRoute
  EditorProjectIdAssetsRoute: typeof EditorProjectIdAssetsRoute
}

const EditorProjectIdRouteChildren: EditorProjectIdRouteChildren = {
  EditorProjectIdProjectRoute: EditorProjectIdProjectRoute,
  EditorProjectIdEditorRoute: EditorProjectIdEditorRouteWithChildren,
  EditorProjectIdBuildRoute: EditorProjectIdBuildRoute,
  EditorProjectIdBoardRoute: EditorProjectIdBoardRoute,
  EditorProjectIdAssetsRoute: EditorProjectIdAssetsRoute,
}

const EditorProjectIdRouteWithChildren = EditorProjectIdRoute._addFileChildren(
  EditorProjectIdRouteChildren,
)

interface GamePackageIdSceneRouteChildren {
  GamePackageIdSceneInventoryRoute: typeof GamePackageIdSceneInventoryRoute
  GamePackageIdSceneBoardRoute: typeof GamePackageIdSceneBoardRoute
}

const GamePackageIdSceneRouteChildren: GamePackageIdSceneRouteChildren = {
  GamePackageIdSceneInventoryRoute: GamePackageIdSceneInventoryRoute,
  GamePackageIdSceneBoardRoute: GamePackageIdSceneBoardRoute,
}

const GamePackageIdSceneRouteWithChildren = GamePackageIdSceneRoute._addFileChildren(
  GamePackageIdSceneRouteChildren,
)

interface EditorRouteChildren {
  EditorWelcomeRoute: typeof EditorWelcomeRoute
  EditorProjectIdRoute: typeof EditorProjectIdRouteWithChildren
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorWelcomeRoute: EditorWelcomeRoute,
  EditorProjectIdRoute: EditorProjectIdRouteWithChildren,
}

const EditorRouteWithChildren = EditorRoute._addFileChildren(
  EditorRouteChildren,
)

interface LauncherRouteChildren {
  LauncherSettingsRoute: typeof LauncherSettingsRoute
  LauncherMainMenuRoute: typeof LauncherMainMenuRoute
  LauncherArkpacksRoute: typeof LauncherArkpacksRoute
  LauncherAboutRoute: typeof LauncherAboutRoute
}

const LauncherRouteChildren: LauncherRouteChildren = {
  LauncherSettingsRoute: LauncherSettingsRoute,
  LauncherMainMenuRoute: LauncherMainMenuRoute,
  LauncherArkpacksRoute: LauncherArkpacksRoute,
  LauncherAboutRoute: LauncherAboutRoute,
}

const LauncherRouteWithChildren = LauncherRoute._addFileChildren(
  LauncherRouteChildren,
)

interface GamePackageIdRouteChildren {
  GamePackageIdCheatsRoute: typeof GamePackageIdCheatsRoute
  GamePackageIdSceneRoute: typeof GamePackageIdSceneRouteWithChildren
  GamePackageIdActionResetRoute: typeof GamePackageIdActionResetRoute
  GamePackageIdActionLeaveRoute: typeof GamePackageIdActionLeaveRoute
  GamePackageIdActionExitRoute: typeof GamePackageIdActionExitRoute
}

const GamePackageIdRouteChildren: GamePackageIdRouteChildren = {
  GamePackageIdCheatsRoute: GamePackageIdCheatsRoute,
  GamePackageIdSceneRoute: GamePackageIdSceneRouteWithChildren,
  GamePackageIdActionResetRoute: GamePackageIdActionResetRoute,
  GamePackageIdActionLeaveRoute: GamePackageIdActionLeaveRoute,
  GamePackageIdActionExitRoute: GamePackageIdActionExitRoute,
}

const GamePackageIdRouteWithChildren = GamePackageIdRoute._addFileChildren(
  GamePackageIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  EditorRoute: EditorRouteWithChildren,
  LauncherRoute: LauncherRouteWithChildren,
  IndexRoute: IndexRoute,
  GamePackageIdRoute: GamePackageIdRouteWithChildren,
  ActionRecoverGameSaveRoute: ActionRecoverGameSaveRoute,
  ActionDiscardFailedGameRoute: ActionDiscardFailedGameRoute,
  ActionLoadGamePackageIdRoute: ActionLoadGamePackageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
